[package]
name = "pesticide"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
lazy_static = "1.5.0"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full"] }

[lib]
proc-macro = true
