[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-g++"
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = 'rsproxy'
[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
